### ISSUE TITLE
Inserts fail for versions of Postgres older than 9.5

### ISSUE THREAD

**Issue by pmn** [lixhq/botkit-storage-postgres#6]
The upsert syntax used [here](https://github.com/lixhq/botkit-storage-postgres/blob/master/src/index.js#L100) will fail for any version of Postgres earlier than 9.5 (the first version that supported the `ON CONFLICT` keyword).

**Comment by emilingerslev** [comment]
Yeah, but I Think the solution is to update the readme with the requirement.
